version: '3.8'

services:
  web:
    build: .
    container_name: dafa_glass_backend
    restart: unless-stopped
    ports:
      - "3007:8000"
    volumes:
      - ./dafa_glass.db:/app/dafa_glass.db
      - ./uploads:/app/uploads
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      - ../client_automation:/app/client_automation
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
